name:      LR-demo
version:   0.2019.8.23
synopsis:  An LALR parsetable generator and interpreter.
license:   BSD-3-Clause
author:    Andreas Abel <andreas.abel@gu.se>
category:  Parsing

tested-with: GHC == 7.0.4
           , GHC == 7.2.2
           , GHC == 7.4.2
           , GHC == 7.6.3
           , GHC == 7.8.4
           , GHC == 7.10.3
           , GHC == 8.0.2
           , GHC == 8.2.2
           , GHC == 8.4.4
           , GHC == 8.6.5
           , GHC == 8.8.4
           , GHC == 8.10.2

dependencies:
  - base >= 4.3 && < 5
  - array
  - containers
  - microlens
  - microlens-th
  - mtl
  - transformers

ghc-options: -Wall

source-dirs: .

executables:
  LR:
    main: LR.hs
  # BugLRec:
  #   main: BugLRec.hs
  # CYK:
  #   main: CYK.hs
