name:      LR-demo
version:   0.2023.3.31
synopsis:  An LALR parsetable generator and interpreter.
license:   BSD-3-Clause
author:    Andreas Abel <andreas.abel@gu.se>
category:  Parsing

# hpack version
spec-version: 0.34.3

# LR.hs uses TypeApplications (from ghc 8.0)
tested-with:
  - GHC == 8.0.2
  - GHC == 8.2.2
  - GHC == 8.4.4
  - GHC == 8.6.5
  - GHC == 8.8.4
  - GHC == 8.10.7
  - GHC == 9.0.2
  - GHC == 9.2.7
  - GHC == 9.4.4

dependencies:
  - base >= 4.9 && < 5
  - array
  - containers >= 0.5.9
      # Set.lookupMin needs containers-0.5.9
  - microlens
  - microlens-th
  - mtl
  - transformers

# ghc-options: -Wall

library:
  source-dirs: src
  # exclude some BNFC-generated files
  when:
    condition: false
    other-modules:
      - LBNF.ErrM
      - LBNF.Skel
      - LBNF.Test

executables:
  lr-demo:
    source-dirs:  lr-demo
    main:         Main.hs
    dependencies: LR-demo

  cyk:
    source-dirs:  main-cyk
    main:         CYK.hs
    ghc-options:  -main-is CYK
      # since the module isn't named Main, we have to pass this option
    dependencies: LR-demo

# Excluding could be possible if issue sol/hpack#402 is implemented
# when:
#   - condition: false
#     other-modules: BugLRec CYK
